### ISSUE TITLE
Country.simplify_countryname("Kosovo*") raises ValueError

### ISSUE THREAD

**Issue by coroa** [OCHA-DAP/hdx-python-country#12]
Hello everyone,

thanks for your fuzzy country name matching routine. It keeps proving very helpful!
I stumbled today over the following special case!

```python
>>> Country.simplify_countryname("Kosovo*")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Country.simplify_countryname("Kosovo*")

File .../hdx/location/country.py:703, in Country.simplify_countryname(cls, country)
    [701](.../hdx/location/country.py?line=700)     countryupper = countryupper_words[0]
    [702](.../hdx/location/country.py?line=701) if countryupper:
--> [703](.../hdx/location/country.py?line=702)     words.remove(countryupper)
    [704](.../hdx/location/country.py?line=703) return countryupper, words

ValueError: list.remove(x): x not in list
```

**Comment by mcarans** [comment]
Thanks for reporting the error. I will investigate why the * causes it to fail.

Please note that the data that drives the library is driven by [this dataset](https://data.humdata.org/dataset/countries-and-territories). Kosovo is not in there. I think that's due to its status of being [recognised by some countries and not others as a state](https://en.wikipedia.org/wiki/International_recognition_of_Kosovo) and the UN's neutrality on the issue. Hence the library will not return an ISO code for Kosovo.

**Comment by mcarans** [comment]
3.2.1 has been released which fixes this issue. Please confirm it works for you and let me know if you come across any problems. If all is good, please close this issue.

**Comment by mcarans** [comment]
Closing.
