### ISSUE TITLE
Option to make `use_live=False` the default?

### ISSUE THREAD

**Issue by garrettc** [OCHA-DAP/hdx-python-country#50]
Hi,

Excellent work on the library, we're finding it incredibly useful in a Django project alongside [django_countries](https://github.com/SmileyChris/django-countries) to decorate countries with extra region info.

Is there any way to set `use_live=False` as the default for queries? We'd like to reduce the amount of external queries we make for performance reasons.

I've searched through the docs and the code and I didn't see anything obvious.

**Comment by mcarans** [comment]
Thank you. There isn't an option for that at the moment. It is something that could be added. Would you consider making a PR?

**Comment by mcarans** [comment]
Note that the static data will be used if you call this first:
```
Country.countriesdata(use_live=False)
```

I will in a any case make an explicit function `set_use_live_default` to set use_live universally so that even if you clear `_countriesdata` and call one of the functions like `get_country_name_from_iso3` it will use the internal file.
