### ISSUE TITLE
Countries that don't quite work

### ISSUE THREAD

**Issue by killthekitten** [OCHA-DAP/hdx-python-country#6]
None of these gives a strict match, and fuzzy results are wrong:

```
Uk ('UKR', False)
England (None, False)
Scotland (None, False)
Brasil (None, False)
America ('ASM', False)
```

What would be the process to fix it?

**Comment by mcarans** [comment]
Sorry for long delay. I will check these soon.

**Comment by mcarans** [comment]
I checked these and the bottom 4 remain an issue.

For England and Scotland, I'm not sure about mapping them to GBR since they aren't a direct match and OCHA doesn't list England or Scotland as alternative names. 

For Brasil, a fix for this would be possible by looking at the spellings in other languages in the OCHA feed.

For America, that might require an override not to return ASM.

**Comment by mcarans** [comment]
In version 2.7.4 of the library, America now returns ('USA', False). I gave more points to exact full word matching to partial word matching.

**Comment by brianmcdonald** [comment]
"Congo, Democratic Republic of the" is the CIA naming convention used for Democratic Republic of the Congo, but currently it resolves to COG instead of COD.

Thanks for your work on this tool. It worked perfectly for me apart from the issues above and some minor spelling issues that the fuzzymatcher wasn't able to catch.

**Comment by mcarans** [comment]
@brianmcdonald Thanks for your kind feedback!

Please can you check as the Congo example you gave resolved to COD for me:

```
from hdx.location.country import Country
Country.get_iso3_country_code_fuzzy('Congo, Democratic Republic of the')
('COD', False)
```

At some point, I will add phonetic matching for country name matching. (It already exists in the code for admin one name matching)

**Comment by brianmcdonald** [comment]
@mcarans My mistake, I think the string that resolved to COG may have been "Congo, Democratic Republic".

**Comment by mcarans** [comment]
Thx @brianmcdonald I will look at that one

**Comment by mcarans** [comment]
@brianmcdonald "Congo, Democratic Republic" is now fixed

**Comment by mcarans** [comment]
Closing, please reopen if still a problem
